In [1]:
import numpy as np
import pickle

In [18]:
output_dict = pickle.load(open('../model/05292018_1006/output_dict.pkl', 'rb'))
data_dict = pickle.load(open("../model/05292018_1006/data.pkl", 'rb'))

In [5]:
output_dict.keys()

dict_keys(['inputs', 'embedding', 'bilstm', 'probability'])

In [7]:
output_dict['embedding'].shape

(202, 5, 25, 100)

In [37]:
# first story
print(output_dict['embedding'][0])
print(output_dict['inputs'][0][0])

[[[-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  ...
  [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
   -0.02212393]
  [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
   -0.02212393]
  [ 0.04362552 -0.00199359  0.02949272 ...  0.02759445 -0.03773167
   -0.03385141]]

 [[-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
    0.04359783]
  ...
  [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
   -0.02212393]
  [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
   -0.02212393]
  [ 0.04362552 -0.00199359  0.02949272 ...  0.02759445 -0.03773167
   -0.

In [36]:
for ix, sentence in enumerate(output_dict['embedding'][0]):
    print('sentence ', ix)
    print(sentence)

sentence  0
[[-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 ...
 [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
  -0.02212393]
 [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
  -0.02212393]
 [ 0.04362552 -0.00199359  0.02949272 ...  0.02759445 -0.03773167
  -0.03385141]]
sentence  1
[[-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 [-0.02793503 -0.00492498 -0.02139579 ... -0.0179299   0.04361938
   0.04359783]
 ...
 [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
  -0.02212393]
 [ 0.02638957 -0.03802272 -0.00032132 ...  0.0197096   0.04025941
  -0.02212393]
 [ 0.04362552 -0.00199359  0.02949272 ...  0.02759445 -0.03773167
  -0.033

In [27]:
for word_emb in output_dict['embedding'][0][0]:
    print(word_emb)

[-0.02793503 -0.00492498 -0.02139579 -0.03567612 -0.02071215  0.03974852
 -0.03612763 -0.00947835 -0.03578285 -0.02684704 -0.00049054  0.01784697
 -0.00436431  0.02967899  0.0409419  -0.03917028 -0.01459731  0.03124313
 -0.03844167 -0.04312757 -0.0206751   0.02183286  0.04955847  0.0314911
 -0.02245173  0.02932331  0.0408945  -0.0238026   0.03051307 -0.04269081
  0.00599668 -0.00563108  0.02942712  0.04737199 -0.01242577  0.01064114
  0.00111858  0.03070829  0.01106723 -0.00489729 -0.01004405 -0.0340744
  0.01860474 -0.00219683 -0.02327712  0.00111819 -0.01753699  0.01327747
 -0.00292218  0.01504878  0.00174227 -0.04070716  0.01786209  0.00751015
 -0.04294823  0.01908146 -0.01356215 -0.02632115  0.02872195 -0.02790256
 -0.0499252  -0.03041872  0.04353775 -0.03160293 -0.04251673  0.00513709
  0.0153018   0.03495351 -0.00242641 -0.04196643  0.04922876  0.04938363
 -0.04541115  0.03087426  0.04129704  0.04426289  0.02418217  0.0167515
 -0.00548052 -0.00956978  0.00646134  0.0306999   0.04

In [21]:
data_dict['w2i_dict']

{'.': 1, '<PAD>': 0, '<UNK>': 5, 'a': 4, 'the': 2, 'to': 3}

In [31]:
untrained_output_dict = pickle.load(open('../model/05292018_1047/output_dict.pkl', 'rb'))
untrained_data_dict =  pickle.load(open('../model/05292018_1047/data.pkl', 'rb'))

In [32]:
for word_emb in untrained_output_dict['embedding'][0][0]:
    print(word_emb)

[ 0.04218421 -0.04334453 -0.03997161 -0.04824827 -0.00669051 -0.00839605
 -0.00150209  0.01286763 -0.04420529 -0.0477893  -0.02221898  0.01429223
  0.02102722 -0.00802733 -0.01333475  0.03448334  0.00831961  0.00740241
  0.0485943  -0.04177304 -0.00964892  0.02038832 -0.00866997  0.02600287
  0.00984909 -0.01705226  0.01057637 -0.03318278  0.02007079  0.03099937
 -0.01040108 -0.0451414   0.00431867  0.03437599  0.04919933 -0.03964586
  0.04287409  0.0060048  -0.04141242 -0.01467061 -0.03826207  0.03961345
  0.01020693  0.03405717  0.03183576  0.0374567  -0.04510701 -0.00923724
  0.0447628  -0.04169309 -0.03003792 -0.00269793  0.01993321 -0.00844197
  0.03860301  0.04951961 -0.04876691 -0.00767121  0.00964109  0.01467553
 -0.04364192 -0.01749787 -0.01631801 -0.02067779  0.00378438 -0.04864162
 -0.03835053 -0.01363285 -0.0166414   0.00269751 -0.01278379 -0.00731487
 -0.01518624 -0.00707688 -0.03416561  0.0195067   0.02277798 -0.00021625
 -0.01803471  0.02242414  0.02806548 -0.04450302 -0

In [38]:
untrained_output_dict['inputs'][0][0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 3, 5,
       5, 5, 1])

In [44]:
untrained_output_dict2 = pickle.load(open('../model/05292018_1141/output_dict.pkl', 'rb'))
untrained_data_dict2 =  pickle.load(open('../model/05292018_1141/data.pkl', 'rb'))
print(untrained_output_dict2['inputs'][0][0][0])
for word_emb in untrained_output_dict2['embedding'][0][0]:
    print(word_emb)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 4 5 5 5 5 1]
[-0.04592877  0.02991116 -0.01432034  0.02283288 -0.00298581 -0.01247749
  0.0001421   0.01997887  0.04555814  0.01366844  0.04961056 -0.04174079
 -0.02862099 -0.00117135 -0.0092053  -0.00205825 -0.036076    0.04508139
 -0.02227746  0.01169366 -0.00653604  0.00767002 -0.02644613  0.00696712
  0.03843595  0.03244958  0.02069695 -0.01296509  0.00444896 -0.03249573
 -0.02568759 -0.01275699  0.04606083  0.03648106  0.02260012 -0.01370997
 -0.03492484 -0.00985477 -0.00250735  0.01024137  0.01522604 -0.04020216
  0.00108106  0.00298332  0.04561328  0.00189024  0.03072226  0.03037972
  0.02792963 -0.01744562 -0.00502289  0.00963811 -0.01618956 -0.00306789
 -0.03922757  0.04997117 -0.0340906   0.00437204  0.01412395 -0.04487893
  0.03572196  0.03590901  0.02722658  0.01974395 -0.00347062 -0.00128482
 -0.04748962  0.04287953 -0.02768137  0.01237563 -0.03582957  0.04900067
  0.03790145  0.03645886 -0.01041753 -0.03999071  0.02066028 -0.00880484

In [42]:
print(untrained_output_dict2['inputs'][0][0])


[[0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 4 5 5 5 5 5 5 5 5 1]
 [0 0 0 0 0 0 0 5 5 3 5 5 5 5 4 5 5 5 3 5 5 5 3 5 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 5 4 5 5 5 3 5 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 2 5 5 5 5 5 5 1]]


In [55]:
# debuging by creating another model
from keras.layers import Input, LSTM, Dense, Embedding, Bidirectional, Flatten, Reshape, Lambda, TimeDistributed, concatenate, multiply
from keras import optimizers
from keras import backend as K
from keras.models import Model

In [75]:
seqlen = 5
storylen= 4
vocab_size = 8
batchsize = 2
output_dim = 50

x = np.array([[[np.random.randint(vocab_size) for _ in range(seqlen)] for _ in range(storylen)] for _ in range(batchsize)])
print("x: \n", x)
pretrained_embeddings = np.array([[i for _ in range(output_dim)] for i in range(vocab_size)])
print("pretrained_embeddings: \n", pretrained_embeddings)

inputs = Input(shape=(storylen, seqlen))
embed_layer = TimeDistributed(Embedding(input_dim = vocab_size, output_dim=output_dim,
                          input_length=seqlen, mask_zero = True,
                          weights=[pretrained_embeddings], trainable=False))
embeddings = embed_layer(inputs)
model = Model(inputs=[inputs], outputs=embeddings)
# no training
model.compile(optimizer='rmsprop', loss='binary_crossentropy')
print("embeddings: \n",  model.predict(x))

x: 
 [[[3 0 7 4 2]
  [4 1 3 5 4]
  [6 2 2 6 3]
  [0 6 5 3 7]]

 [[0 6 6 3 0]
  [4 3 4 3 5]
  [0 7 6 6 6]
  [1 4 4 5 2]]]
pretrained_embeddings: 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
  3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
  4 4 4 4 4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
  6 6 6 6 6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
  7 7 7 7 7 7 7 7 7 7 7 7 7 7]]
embeddings: 


In [76]:
x.shape

(2, 4, 5)

In [66]:
model.predict(x).shape

(2, 4, 5, 50)

In [47]:
x

6